#!/bin/bash
g++ -o ./optional ./optional.cpp `sdl-config --libs --cflags` -lSDL_image -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/libgtop-2.0 -I/usr/include/qt4/ -lQtCore -I/usr/lib/libgtop-2.0/include -lglib-2.0 -lglib-2.0 -lgtop-2.0 -lgtop-2.0
