/* Eyes
 * Copyright (C) 2011  Krzysztof Mędrzycki, Damian Chiliński
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

#ifndef _eyes_eyes_hxx
#define _eyes_eyes_hxx

extern const double versiond;
extern const char *verstr;

/**
 * \mainpage Eyes
 *
 * \section intro Introduction
 *
 * Some introduction to Eyes Project
 */

#include <QWidget>
#include <QGraphicsScene>
#include <QImage>
#include <QPixmap>
#include <QBitmap>
#include <QMap>
#include <QList>
#include <QMouseEvent>
#include <QtConcurrentRun>
#include <QTimer>
#include <QThread>
#include <QTime>
#include <libconfig.h++>
#include <ostream>

#include "defines.hxx"
#include "animation.hxx"
#include "configuration.hxx"

#define EYE_S       60
#define EYE_M       9
#define NUM_LAYERS  3

extern int  eye_s,
            eye_m,
            eyes_w,
            eyes_h;
extern bool images_ready;

#define EYES_W  320
#define EYES_H  80

using namespace libconfig;
using namespace std;

class eyes_clapper;
class eyes_looker;
class Core;

QString get_face_suffix ( QString face );

enum eyes_flag
{
    clapper,
};

/**
 * Main widget for eyes. Draw eyes based on state generated by \p Core.
 */
class eyes_view : public QWidget
{
    Q_OBJECT
public:
    enum Layers
    {
        HOT     = 0,
        SHY     = 1,
        SLEEPY  = 2
    };

    /**
     * Construct eyes_view with color \p color.
     * @param color Color of the eyes.
     */
    explicit            eyes_view           ( QWidget * parent, QString color );
    /// Destruct eyes_view.
                        ~eyes_view          ();
    /// Called when window need to be redrawed. Redraw eyes.
    void                paintEvent          ( QPaintEvent * );
    void                closeEvent          ( QCloseEvent * ev );
    /**
     * Called by \p Core when \p bulwers is updated.
     * @param core_stats state of bulwers.
     */
    void                set_face            ( QString nface );
    void                set_eyes            ( QString neyes );
    void                set_eyes_position   ( int nx1, int nx2, int ny );
    void                set_mirror_position ( double nx1, double nx2, double ny );
    void                set_animation       ( QString start, QString end, int from, int to );
    void                anims_send          ( QString fac, QString nstart, QString nend, unsigned short nfrom, unsigned short nto );
    void                send_eyes           ( QString neyes );
    void                toggle_layer        ( Layers layer, bool onoff );
    void                set_layer           ( Layers layer, QString face );
    void                reload_eyes         ();
    void                graphics_prepare    ();
    void                anims_reload        ();
    void                setFlag             ( eyes_flag flag, bool value );
    int                 heightForWidth      ( int w )                               const;
    int                 get_next_clap_delay ();
    /// @return position x of left eye.
    inline int          get_eyes_x1         () { return epx1; }
    /// @return position x of right eye.
    inline int          get_eyes_x2         () { return epx2; }
    /// @return position y of eyes.
    inline int          get_eyes_y          () { return epy; }
    /// @return position x of left mirror.
    inline double       get_mirror_x1       () { return mpx1; }
    /// @return position x of right mirror.
    inline double       get_mirror_x2       () { return mpx2; }
    /// @return position y of mirrors.
    inline double       get_mirror_y        () { return mpy; }
    QVariant            inputMethodQuery    ( Qt::InputMethodQuery query )          const;
    QSize               sizeHint            ()                                      const;
    QString             get_face            ();
    QString	            get_face_next       ();
    QString             get_color_suffix    () { return color; }
signals:
    void                mousemoved          ( int x, int y );
    void                mouseentered        ();
public slots:
    void                mousePressEvent     ( QMouseEvent * ev );
    void                mouseMoveEvent      ( QMouseEvent * ev );
    void                enterEvent          ( QEvent * );
private:
    struct _layer
    {
        QString face;
        bool    drawable;
    };

    void                open_images         ( QString folder );
    _layer                * layers;
    QTimer                * timer;
    QTime                   time;
    QWidget               * win;
    QBitmap                 mask;
    QPixmap               * area;
    QString                 eye,
                            face,
                            theme,
                            face_next,
                            face_queue,
                            spec,
                            color;
    QMap<QString,QPixmap>   pics;
    QMap<QString,QPixmap>   eyes;
    QFuture<void>           c_main;
    int                     px,
                            py,
                            epx1,
                            epx2,
                            epy;
    double                   mpx1,
                            mpx2,
                            mpy;
    bool                    clapper_f;
    void                  * locker;
    eyes_clapper          * clapper;
    eyes_looker           * looker;
    Configuration         * set;
    Core                  * core;
};

/**
 * Module that controll claping animations.
 */
class eyes_clapper : public QThread
{
    Q_OBJECT
public:
    /**
     * Construct \p eyes_clapper.
     * @param neyes pointer to \p eyes_view to controll.
     */
    explicit    eyes_clapper        ( eyes_view * neyes );
    int         get_next_clap_delay ();
    /// Start timer.
    void        run                 ();
    /// Sets actual animation.
    void        set_animation       ( QString nstart, QString nend, int nfrom, int nto );
public slots:
    /// Called on timer tick, ...?.
    void        clap                ();
private:
    int                         stage,
                                from,
                                to,
                                size1,
                                size2,
                                min_dl,
                                max_dl;
    eyes_view                 * eyes;
    QTime                       time;
    QTimer                    * timer;
    QString                     face,
                                start,
                                end;
    QMap<QString,animation*>    animations;
};

/**
 * Module that controll eyes looking.
 */
class eyes_looker : public QObject
{
    Q_OBJECT
public:
    /**
     * Construct \p eyes_looker.
     * @param neyes pointer to \p eyes_view to controll.
     */
            eyes_looker ( eyes_view * eyes );
    void    run ();
public slots:
    /// Called on timer tick, ...?.
    void    look ();
private:
    eyes_view * eyes;
    QTimer    * timer;
    int         min_dx,
                max_dx,
                min_dy,
                max_dy,
                min_dl,
                max_dl,
                bmin_x,
                bmax_x,
                bmin_y,
                bmax_y;
};

class Core : public QObject
{
    Q_OBJECT
public:
                    Core            ( eyes_view * );
    void            bulwers_update  (),
                    bulwers_init    (),
                    gui_refresh     (),
                    gui_init        (),
                    load_config     (),
                    run             (),
                    graphics_prepare(),
                    autocalc_reload ( Configuration * set ),
                    autocalc_init   ();
    bool            wake_up_prepare ();

    QString face_prev;
    bool    wake_up;
public slots:
    void    on_timer_tick   ();
    void    handle_mouse    ( int x, int y );
    void    handle_enter    ();
private:
    QTimer        * timer;
    eyes_view     * eyes;
};

extern eyes_view * eyes;

#endif //eyes_eyes_hxx
