#############################################################################
# Makefile for building: eyes
# Generated by qmake (2.01a) (Qt 4.6.3) on: Fri Mar 4 20:30:35 2011
# Project:  eyes.pro
# Template: app
# Command: /usr/bin/qmake -spec /usr/share/qt4/mkspecs/linux-g++ -unix CONFIG+=debug -o Makefile eyes.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/libgtop-2.0 -I/usr/lib/libgtop-2.0/include -I/usr/local/include -I.
LINK          = g++
LFLAGS        = -Wl,-rpath,/usr/lib64/qt4
LIBS          = $(SUBLIBS)  -L/usr/lib64/qt4 /usr/lib/libglib-2.0.so /usr/lib/libgtop-2.0.so /usr/local/lib/libconfig++.so -lQtGui -L/usr/lib64 -L/usr/lib64/qt4 -L/usr/X11R6/lib -lQtCore -lgthread-2.0 -lrt -lglib-2.0 -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = eyes_ui.cpp \
		eyes_view.cpp \
		eyes_clapper.cc \
		animation.cc \
		eyes_looker.cc \
		eyes_cfg.cc \
		core_new.cpp moc_eyes_view.cpp
OBJECTS       = eyes_ui.o \
		eyes_view.o \
		eyes_clapper.o \
		animation.o \
		eyes_looker.o \
		eyes_cfg.o \
		core_new.o \
		moc_eyes_view.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		eyes.pro
QMAKE_TARGET  = eyes
DESTDIR       = 
TARGET        = eyes

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: eyes.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib64/qt4/libQtGui.prl \
		/usr/lib64/qt4/libQtCore.prl
	$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -unix CONFIG+=debug -o Makefile eyes.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/debug.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib64/qt4/libQtGui.prl:
/usr/lib64/qt4/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -unix CONFIG+=debug -o Makefile eyes.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/eyes1.0.0 || $(MKDIR) .tmp/eyes1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/eyes1.0.0/ && $(COPY_FILE) --parents eyes_view.h bulwers.h eyes_info.h defines.hxx clap_animations.hxx animation.hxx eyes_cfg.hxx core_new.hxx .tmp/eyes1.0.0/ && $(COPY_FILE) --parents eyes_ui.cpp eyes_view.cpp eyes_clapper.cc animation.cc eyes_looker.cc eyes_cfg.cc core_new.cpp .tmp/eyes1.0.0/ && (cd `dirname .tmp/eyes1.0.0` && $(TAR) eyes1.0.0.tar eyes1.0.0 && $(COMPRESS) eyes1.0.0.tar) && $(MOVE) `dirname .tmp/eyes1.0.0`/eyes1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/eyes1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_eyes_view.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_eyes_view.cpp
moc_eyes_view.cpp: bulwers.h \
		defines.hxx \
		animation.hxx \
		eyes_view.h
	/usr/bin/moc $(DEFINES) $(INCPATH) eyes_view.h -o moc_eyes_view.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

eyes_ui.o: eyes_ui.cpp eyes_view.h \
		bulwers.h \
		defines.hxx \
		animation.hxx \
		eyes_info.h \
		eyes_cfg.hxx
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o eyes_ui.o eyes_ui.cpp

eyes_view.o: eyes_view.cpp eyes_view.h \
		bulwers.h \
		defines.hxx \
		animation.hxx \
		eyes_info.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o eyes_view.o eyes_view.cpp

eyes_clapper.o: eyes_clapper.cc eyes_view.h \
		bulwers.h \
		defines.hxx \
		animation.hxx \
		clap_animations.hxx
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o eyes_clapper.o eyes_clapper.cc

animation.o: animation.cc animation.hxx \
		defines.hxx
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o animation.o animation.cc

eyes_looker.o: eyes_looker.cc eyes_view.h \
		bulwers.h \
		defines.hxx \
		animation.hxx
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o eyes_looker.o eyes_looker.cc

eyes_cfg.o: eyes_cfg.cc eyes_cfg.hxx
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o eyes_cfg.o eyes_cfg.cc

core_new.o: core_new.cpp /usr/include/qt4/Qt/qstring.h \
		/usr/include/qt4/Qt/qvector.h \
		/usr/include/qt4/Qt/qregexp.h \
		/usr/include/qt4/Qt/qstringlist.h \
		core_new.hxx \
		eyes_view.h \
		bulwers.h \
		defines.hxx \
		animation.hxx
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o core_new.o core_new.cpp

moc_eyes_view.o: moc_eyes_view.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_eyes_view.o moc_eyes_view.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

